# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: alertmanager
#   namespace: argocd
# spec:
#   destination:
#     namespace: monitoring
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     directory:
#       jsonnet: {}
#       recurse: true
#     path: Core-apps/deploy/dev-cluster/yaml/alertmanager
#     repoURL: https://github.com/urmas-villem/ArgoTest.git
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
