apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: default